# Generated by Django 2.0.2 on 2018-08-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macuos', '0002_auto_20180729_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnail/', verbose_name='サムネイル'),
        ),
    ]
